image: ruby:2.5
stages:
  - build

variables:
  LANG: "C.UTF-8"

before_script:
  - gem install bundler

build_site:
  stage: build
  only:
    - master
  script:
    - bundle install
    - bundle exec jekyll build 
