- platform: Windows, 64-bit
  id: windows
  icon: icon-windows
  cli_url: win64
  cli_hash: 82db8f99fa4b2900f78c282c2d99309b79da544824f9cdb10d0b80ceb511c5ed
  gui_url: win64
  gui_hash: 947efb72418d9ee60ccb0a2afa1f85553fa6a777a0a4e0f89f353592c84e00dc
  cli_version: 0.13.0.2
  gui_version: 0.12.3.0
  tag: Beryllium Bullet
  blockchain: win

- platform: Windows, 32-bit
  icon: icon-windows
  cli_url: win32
  cli_hash: f9fad998af2c439dce45b8210784b228c8a99dced926e9bec3522af2a213c747
  version: 0.13.0.2
  tag: Beryllium Bullet
  blockchain: win

- platform: Mac OS X, 64-bit
  id: mac
  icon: icon-apple
  cli_url: mac64
  cli_hash: bb0f197c9e43e183b9af48dfbc4f7b492568fe01d2c23c66ec3632c8aa85e4e9
  gui_url: mac64
  gui_hash: 90a9fa02e7bcef653b034f8a0365f16ec96cd553791546df2200a3c2591d5104
  cli_version: 0.13.0.2
  gui_version: 0.12.3.0
  tag: Beryllium Bullet
  blockchain: mac

- platform: Linux, 64-bit
  id: linux
  icon: icon-linux
  cli_url: linux64
  cli_hash: a59fc0fffb325b4f92a5b500438bf340ddbf78e91581eb4df95ad2d5e5fb42a8
  gui_url: linux64
  gui_hash: dcf0a103589b8e71cdb8298dec96610f9f50b25e8f48afef5186d4c460a4ecae
  cli_version: 0.13.0.2
  gui_version: 0.12.3.0
  tag: Beryllium Bullet
  blockchain: linux

- platform: Linux, 32-bit
  icon: icon-linux
  cli_url: linux32
  cli_hash: 87396e833859cbafff53db753443f8f94a962d9738cb0f69ea9d0b3c940960e6
  gui_url: linux32
  gui_hash: 6858519657add070aeedb03a22d4661ec1b868acdd0b3437fe45e6b640ea4e3b
  cli_version: 0.13.0.2
  gui_version: 0.12.3.0
  tag: Beryllium Bullet
  blockchain: linux

- platform: ARMv7
  id: arm
  icon: icon-arm
  cli_url: linuxarm7
  cli_hash: 839bddb01214acb8f7bc12181b206e1e8d99314337addef7ba850b15c32dc685
  version: 0.12.3.0
  tag: Lithium Luna
  blockchain: arm

- platform: ARMv8
  id: arm
  icon: icon-arm
  cli_url: linuxarm8
  cli_hash: a6e994dc9fcec7259b656752a6fc0f9686bad47da9deec0f50398718cd9b9be8
  version: 0.12.3.0
  tag: Lithium Luna
  blockchain: arm

- platform: Source Code & Blockchain
  id: source
  icon: icon-github
  cli_url: https://github.com/monero-project/monero
  cli_hash: source
  version: Bleeding edge (possibly unstable)
  
- platform: Mobile & Light Wallets
  id: mobilelight
  
- platform: Hardware Wallets
  id: hardware
