- platform: Windows, 64-bit
  id: windows
  icon: icon-windows
  cli_url: win64
  cli_hash: ca4367c565026ea23bf90180cdd750a1d6adfab36ee19435e91ed740a369a6fc
  gui_url: win64
  gui_hash: cecb32d57684c9ec719f56ef72464413986d8bda93b2d5f51852eb1946e51993
  gui_installer_url: win64install
  gui_installer_hash: 4c0ceb81361a4b69bff6cd5a47ef94cfd2992796fb25ca3923aed51d6fcd48bd
  cli_version: 0.14.1.0
  gui_version: 0.14.1.0
  gui_installer_version: 0.14.0.0
  tag: Boron Butterfly
  blockchain: win

- platform: Windows, 32-bit
  icon: icon-windows
  cli_url: win32
  cli_hash: ed26ad4c7f3fc15893c615e438a76f91c8c5c18e29d32bf350e126beecc2877f
  version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: win

- platform: Mac OS X, 64-bit
  id: mac
  icon: icon-apple
  cli_url: mac64
  cli_hash: 96ae0af11cdf4ad66326ae128675d6476088719ed3d226a7dbc903767f3a858a
  gui_url: mac64
  gui_hash: b0d3f906265a27b2b60090466e693d7f15a00bb8d058d8fad89f0b10c50fe6ea
  cli_version: 0.14.1.0
  gui_version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: mac

- platform: Linux, 64-bit
  id: linux
  icon: icon-linux
  cli_url: linux64
  cli_hash: 2b95118f53d98d542a85f8732b84ba13b3cd20517ccb40332b0edd0ddf4f8c62
  gui_url: linux64
  gui_hash: 51739f0472ccbd49832a5828ca1000ebb1ce63b19dd57507b7905739bf8cf238
  cli_version: 0.14.1.0
  gui_version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: linux

- platform: Linux, 32-bit
  icon: icon-linux
  cli_url: linux32
  cli_hash: a31bca6e556064d56f7a37ddbea26408902e5f387e5b67fa5b0999ca299b8eef
  cli_version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: linux

- platform: FreeBSD, 64-bit
  id: bsd
  icon: icon-freebsd
  cli_url: freebsd64
  cli_hash: 17f21d718ad0ba6d7965004ed8390a01a9ccf06ef95891ab26bd6592a7169c58
  version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: freebsd

- platform: ARMv8
  id: arm
  icon: icon-arm
  cli_url: linuxarm8
  cli_hash: cf46a1cdea6f7983697df6dfbbb184b6dd23e816ed156899070885a78b310171
  version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: arm

- platform: ARMv7
  id: arm
  icon: icon-arm
  cli_url: linuxarm7
  cli_hash: b95903a0f1b0c15cefdf59814fe12e3597a3322ae6d0567c732f0ab79c877724
  version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: arm

- platform: Source Code & Blockchain
  id: source
  icon: icon-github
  cli_url: https://github.com/monero-project/monero
  mirror1: https://git.xmr.pm/monero-project/monero
  cli_hash: source
  version: Bleeding edge (possibly unstable)

- platform: Mobile & Light Wallets
  id: mobilelight

- platform: Hardware Wallets
  id: hardware
