- platform: Windows, 64-bit
  id: windows
  icon: icon-windows
  cli_url: win64
  cli_hash: 6b72b3836d179eb517154bbcb8e2119b168ae9d1054866a438aaeab9521f795f
  gui_url: win64
  gui_hash: cecb32d57684c9ec719f56ef72464413986d8bda93b2d5f51852eb1946e51993
  gui_installer_url: win64install
  gui_installer_hash: aff1a4780d7a0814bc9bf8927815e104f6afee5b3c3edec454c56a994e87e50f
  cli_version: 0.15.0.0
  gui_version: 0.14.1.0
  gui_installer_version: 0.14.1.0
  tag: Carbon Chamaeleon
  blockchain: win

- platform: Windows, 32-bit
  icon: icon-windows
  cli_url: win32
  cli_hash: b4856d0d3389497bf103d5a4dc4e73c6a39e5be20736b3e0286e76f100c508b6
  version: 0.15.0.0
  tag: Carbon Chamaeleon
  blockchain: win

- platform: Mac OS X, 64-bit
  id: mac
  icon: icon-apple
  cli_url: mac64
  cli_hash: bca6b776e7e906fcda4c829aa8666eb9d92014450b87a6723a7c6eda6d6e7de1
  gui_url: mac64
  gui_hash: b0d3f906265a27b2b60090466e693d7f15a00bb8d058d8fad89f0b10c50fe6ea
  cli_version: 0.15.0.0
  gui_version: 0.14.1.0
  tag: Carbon Chamaeleon
  blockchain: mac

- platform: Linux, 64-bit
  id: linux
  icon: icon-linux
  cli_url: linux64
  cli_hash: 53d9da55137f83b1e7571aef090b0784d9f04a980115b5c391455374729393f3
  gui_url: linux64
  gui_hash: 51739f0472ccbd49832a5828ca1000ebb1ce63b19dd57507b7905739bf8cf238
  cli_version: 0.15.0.0
  gui_version: 0.14.1.0
  tag: Carbon Chamaeleon
  blockchain: linux

- platform: Linux, 32-bit
  icon: icon-linux
  cli_url: linux32
  cli_hash: 2197d04f4ffad4e1344b2648273f0be152de637bafc5d940cdf215cbc50e1f79
  cli_version: 0.15.0.0
  tag: Carbon Chamaeleon
  blockchain: linux

- platform: FreeBSD, 64-bit
  id: bsd
  icon: icon-freebsd
  cli_url: freebsd64
  cli_hash: d070d71d1bc9b5e7555e6fe5f8e90c44ff06f28cafc34de9c8f821a317e4e6fe
  version: 0.14.1.2
  tag: Carbon Chamaeleon
  blockchain: freebsd

- platform: ARMv8
  id: arm
  icon: icon-arm
  cli_url: linuxarm8
  cli_hash: f92f0acbc49076ad57337b5928981cd72c01aabe6a8eb69a1782f7fa1388fb77
  version: 0.15.0.0
  tag: Carbon Chamaeleon
  blockchain: arm

- platform: ARMv7
  id: arm
  icon: icon-arm
  cli_url: linuxarm7
  cli_hash: 326f783ffde78694b2820c95aa310ead00bb5876937ed4edf9c1abd6b6aadc02
  version: 0.15.0.0
  tag: Carbon Chamaeleon
  blockchain: arm

- platform: Source Code & Blockchain
  id: source
  icon: icon-github
  cli_url: https://github.com/monero-project/monero
  mirror1: https://git.xmr.pm/monero-project/monero
  cli_hash: source
  version: Bleeding edge (possibly unstable)

- platform: Mobile & Light Wallets
  id: mobilelight

- platform: Hardware Wallets
  id: hardware
