- platform: Windows, 64-bit
  id: windows
  icon: icon-windows
  cli_url: win64
  cli_hash: ee68ef8d4b3309cca9e68ee272919c222021804e493c2549c910ef370dfe595a
  gui_url: win64
  gui_hash: ff1b1467dc6252462e5e7818485857ad2ee253712670ff7f5716aa57241577c7
  cli_version: 0.14.0.2
  gui_version: 0.13.0.4
  tag: Boron Butterfly
  blockchain: win

- platform: Windows, 32-bit
  icon: icon-windows
  cli_url: win32
  cli_hash: e471015b4851aef259758fc6a98805655c69db53f29b68362f63dccb496f6e55
  gui_url: win32
  gui_hash: 50feee5c42c7342140a7e5c95a88d330262bebf3b844817ed49e4be86787795b
  cli_version: 0.14.0.2
  gui_version: 0.13.0.4
  tag: Boron Butterfly
  blockchain: win

- platform: Mac OS X, 64-bit
  id: mac
  icon: icon-apple
  cli_url: mac64
  cli_hash: 255ae412daa04a0e0143325a7763e0574a27e7be86f4ef48582efde9fc07241c
  gui_url: mac64
  gui_hash: c425f1b984cf00ffd1a9f1322e5da876aa07c106e975ca9fe08ee0a2d2956335
  cli_version: 0.14.0.2
  gui_version: 0.13.0.4
  tag: Boron Butterfly
  blockchain: mac

- platform: Linux, 64-bit
  id: linux
  icon: icon-linux
  cli_url: linux64
  cli_hash: 4dd5cd9976eda6b33b16821e79e671527b78a1c9bfb3d973efe84b824642dd21
  gui_url: linux64
  gui_hash: 284d61981204246425a520087723edb65155c89b9cb807750dca8c8687156679
  cli_version: 0.14.0.2
  gui_version: 0.13.0.4
  tag: Boron Butterfly
  blockchain: linux

- platform: Linux, 32-bit
  icon: icon-linux
  cli_url: linux32
  cli_hash: be6ad1de8f16bdeeaf5f4f36f93dcaad97eaa8ff02449b7fffed1abe21605e0e
  gui_url: linux32
  gui_hash: 53750002c3f630457a397ef097929eb3eaa204ac393ff65ef1a05916872eb788
  cli_version: 0.14.0.2
  gui_version: 0.13.0.4
  tag: Boron Butterfly
  blockchain: linux

- platform: FreeBSD, 64-bit
  id: bsd
  icon: icon-freebsd
  cli_url: freebsd64
  cli_hash: 3fc84b1ca32d99d436d304ee1401e911bbc1b0e1fc0314dc3f879df15e8428f3
  version: 0.14.0.2
  tag: Boron Butterfly
  blockchain: freebsd

- platform: ARMv8
  id: arm
  icon: icon-arm
  cli_url: linuxarm8
  cli_hash: 6558f4cff51a1f25c9979a57fc31edd46caaaeda18c81c76e1dc6c94144525c6
  version: 0.14.0.2
  tag: Boron Butterfly
  blockchain: arm

- platform: ARMv7
  id: arm
  icon: icon-arm
  cli_url: linuxarm7
  cli_hash: f0e3d82354a9a25776bd2081f2bb1c081a8589ffb783e765ec974d211174236a
  version: 0.14.0.2
  tag: Boron Butterfly
  blockchain: arm

- platform: Source Code & Blockchain
  id: source
  icon: icon-github
  cli_url: https://github.com/monero-project/monero
  mirror1: https://git.pwned.systems/monero-project/monero
  cli_hash: source
  version: Bleeding edge (possibly unstable)
  
- platform: Mobile & Light Wallets
  id: mobilelight
  
- platform: Hardware Wallets
  id: hardware
