- platform: Windows, 64-bit
  id: windows
  icon: icon-windows
  cli_url: win64
  cli_hash: a11b58d8ad8f5e3a4b3fe076ea2d620ef0e2efb33d5e2506e68458253ac14421
  gui_url: win64
  gui_hash: cecb32d57684c9ec719f56ef72464413986d8bda93b2d5f51852eb1946e51993
  gui_installer_url: win64install
  gui_installer_hash: aff1a4780d7a0814bc9bf8927815e104f6afee5b3c3edec454c56a994e87e50f
  cli_version: 0.14.1.2
  gui_version: 0.14.1.0
  gui_installer_version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: win

- platform: Windows, 32-bit
  icon: icon-windows
  cli_url: win32
  cli_hash: 9f4d6a1386e09c29c400096f8053838ceecb8c5754fe584a6bc310fda19ce105
  version: 0.14.1.2
  tag: Boron Butterfly
  blockchain: win

- platform: Mac OS X, 64-bit
  id: mac
  icon: icon-apple
  cli_url: mac64
  cli_hash: 038abb39dfb66d56cf03537277d8dade6524c10dd94b89bfc6203c301b48e4df
  gui_url: mac64
  gui_hash: b0d3f906265a27b2b60090466e693d7f15a00bb8d058d8fad89f0b10c50fe6ea
  cli_version: 0.14.1.2
  gui_version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: mac

- platform: Linux, 64-bit
  id: linux
  icon: icon-linux
  cli_url: linux64
  cli_hash: a4d1ddb9a6f36fcb985a3c07101756f544a5c9f797edd0885dab4a9de27a6228
  gui_url: linux64
  gui_hash: 51739f0472ccbd49832a5828ca1000ebb1ce63b19dd57507b7905739bf8cf238
  cli_version: 0.14.1.2
  gui_version: 0.14.1.0
  tag: Boron Butterfly
  blockchain: linux

- platform: Linux, 32-bit
  icon: icon-linux
  cli_url: linux32
  cli_hash: ede3b29d085d25058268cea932190c77c276618d97fd2a859002dc01de0c54cb
  cli_version: 0.14.1.2
  tag: Boron Butterfly
  blockchain: linux

- platform: FreeBSD, 64-bit
  id: bsd
  icon: icon-freebsd
  cli_url: freebsd64
  cli_hash: d070d71d1bc9b5e7555e6fe5f8e90c44ff06f28cafc34de9c8f821a317e4e6fe
  version: 0.14.1.2
  tag: Boron Butterfly
  blockchain: freebsd

- platform: ARMv8
  id: arm
  icon: icon-arm
  cli_url: linuxarm8
  cli_hash: d462fd0f2e4010b6717de2cf6aa8d04a50e56a8fdfd3735230a2a36e63cdb9fb
  version: 0.14.1.2
  tag: Boron Butterfly
  blockchain: arm

- platform: ARMv7
  id: arm
  icon: icon-arm
  cli_url: linuxarm7
  cli_hash: 7f040bf1d0fec4f76064f5c8af249f1df9d5a6decd6846c3080bd749b2516280
  version: 0.14.1.2
  tag: Boron Butterfly
  blockchain: arm

- platform: Source Code & Blockchain
  id: source
  icon: icon-github
  cli_url: https://github.com/monero-project/monero
  mirror1: https://git.xmr.pm/monero-project/monero
  cli_hash: source
  version: Bleeding edge (possibly unstable)

- platform: Mobile & Light Wallets
  id: mobilelight

- platform: Hardware Wallets
  id: hardware
